---
namespace: ipfabric
name: ansible
version: 1.0.0
readme: README.md
authors:
- IPFabric <solution.architecture@ipfabric.io>
description: Ansible Collection for managing IPFabric
license_file: 'LICENSE'
tags:
  - ipfabric
  - discovery
repository: https://github.com/community-fabric/ipfabric-ansible
#documentation: http://docs.example.com
homepage: https://github.com/community-fabric/ipfabric-ansible
issues: https://github.com/community-fabric/ipfabric-ansible/issues
build_ignore: []
